name = "SGtoRFEM"
uuid = "c4e901a8-bc5e-4a22-8db3-7c88164cb485"
version = "0.1.0"
authors = ["Josua A <cylconehopper@gmail.com>"]

[deps]
XML = "69e8c417-849c-5b4e-97c4-699997e3b022"

[compat]
XML = "0.4.0"
julia = "1.6"
